[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/sarahstrange/Programming/newt.json"

[programs.localnet]
mpl_auction_house="hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "target/deploy/mpl_token_metadata.so"

[[test.genesis]]
address = "hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk"
program = "target/deploy/mpl_auction_house.so"

[[test.genesis]]
address = "qntmGodpGkrM42mN68VCZHXnKqDCT8rdY23wFcXCLPd"
program = "target/deploy/mpl_token_entangler.so"

[[test.genesis]]
address = "3hPhRB3M16RerH3B8j56P8ZSnFuKs2ZEQojfSspnhfNW"
program = "target/deploy/mpl_gumdrop.so"

[workspace]
members = [
  "token-entangler/program",
  "token-metadata/program",
  "auction-house/program"
] 
